version: '3.7'

services:
  node:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: murderer-api
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
