version: '3.7'

services:
  node:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: murderer-api
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"

  mongo:
    image: mongo
    restart: always
    logging:
      driver: none
    ports:
      - 27020:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
